spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        format_sql: true
        default_batch_fetch_size: 100

springdoc:
  packages-to-scan: com.money
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

app:
  oauth:
    google-client-id: test
  token:
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    expiration:
      access-token: 86400000
      refresh-token: 384000000
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none


app:
  oauth:
    google-client-id: ${GOOGLE_CLIENT_ID}
  token:
    secret: ${JWT_SECRET}
    expiration:
      access-token: 86400000
      refresh-token: 604800000
